steps:

- id: 'unit-test-core'
  name: 'maven:${_MAVEN_VERSION}'
  entrypoint: 'mvn'
  args: ['-s', '/workspace/cloudbuild-settings.xml', '--projects', 'core', '-D${_TEST_BUCKET}', 'test']
- id: 'unit-test-ingestion'
  name: 'maven:${_MAVEN_VERSION}'
  entrypoint: 'mvn'
  args: ['-s', '/workspace/cloudbuild-settings.xml', '--projects', 'ingestion', '-D${_TEST_BUCKET}', 'test']
- id: 'unit-test-serving'
  name: 'maven:${_MAVEN_VERSION}'
  entrypoint: 'mvn'
  args: ['-s', '/workspace/cloudbuild-settings.xml', '--projects', 'serving', '-D${_TEST_BUCKET}', 'test']
- id: 'unit-test-cli-setup'
  name: 'golang:1.12'
  args: ['go', 'get', '-u', 'github.com/jstemmer/go-junit-report']
- id: 'unit-test-cli-run'
  name: 'golang:1.12'
  args: ['go', 'test', '-v', './cli/feast/...']
- id: 'unit-test-python-sdk'
  name: 'python:3.6.9-buster'
  dir: '/workspace/sdk/python'
  env: ['SKIP_BIGQUERY_TEST=true'] # TODO: Configure project/permissions and re-enable
  entrypoint: 'sh'
  args: ['-c', 'pip install -r requirements-test.txt && pip install . && pytest ./tests']

- id: 'integration-test-setup'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args: ['-c', 'echo TODO: prepare_integration_test.sh']
- id: 'integration-test-run'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args: ['-c', 'echo TODO: install_feast_and_run_e2e_test.sh']
- id: 'integration-test-teardown'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args: ['-c', 'echo TODO: cleanup_feast_installation.sh']

- id: 'build-proto'
  name: 'znly/protoc'
  dir: '/workspace/protos'
  entrypoint: 'make'
  args: ['gen-go', 'gen-python']
- id: 'build-cli'
  name: 'golang:1.12'
  dir: '/workspace/cli'
  entrypoint: 'make'
  args: ['build-all']
- id: 'build-java'
  name: 'maven:${_MAVEN_VERSION}'
  entrypoint: 'mvn'
  args: ['-s', '/workspace/cloudbuild-settings.xml', '--projects', 'core,ingestion,serving', '-Drevision=ff-${SHORT_SHA}', '-DskipTests=true', '--batch-mode', 'package']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/feast-core:ff-${SHORT_SHA}', '-f', 'docker/core/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/feast-serving:ff-${SHORT_SHA}', '-f', 'docker/serving/Dockerfile', '.']

images:
- gcr.io/${PROJECT_ID}/feast-core:ff-${SHORT_SHA}
- gcr.io/${PROJECT_ID}/feast-serving:ff-${SHORT_SHA}

options:
  machineType: N1_HIGHCPU_8
  env:
  - GO111MODULE=on
  - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2
  volumes:
  - name: go-modules
    path: /go
  - name: m2_cache
    path: /cache/.m2

substitutions:
  _TEST_BUCKET: testbucket=dev-konnekt-data-deep-1-feast-tmp
  _MAVEN_VERSION: 3.6.2-jdk-11-slim

tags: ['team__konnekt', 'repo__konnekt_data_feast', 'commit__${SHORT_SHA}', 'slack__konnekt-devops-test']
