steps:

# Setup
- id: m2-cahce-pull
  waitFor: ['-']
  name: gcr.io/cloud-builders/gsutil
  args:
  - -o GSUtil:parallel_process_count=16
  - -o GSUtil:parallel_thread_count=1
  - -m
  - rsync
  - -j
  - pom,sha1
  - -r
  - gs://dev-konnekt-data-deep-1-feast-tmp/cache/m2
  - /cache/m2

# JAVA
- id: unit-test-core
  waitFor: ['-']
  name: 'maven:${_MAVEN_VERSION}'
  entrypoint: mvn
  args: ['--settings=cloudbuild-settings.xml', '--projects=core', '-Drevision=ff-${SHORT_SHA}', '-Dtestbucket=${_TEST_BUCKET}', 'test']
- id: unit-test-ingestion
  waitFor: ['unit-test-core']
  name: 'maven:${_MAVEN_VERSION}'
  entrypoint: mvn
  args: ['--settings=cloudbuild-settings.xml', '--projects=ingestion', '-Drevision=ff-${SHORT_SHA}', '-Dtestbucket=${_TEST_BUCKET}', 'test']
- id: unit-test-serving
  waitFor: ['unit-test-ingestion']
  name: 'maven:${_MAVEN_VERSION}'
  entrypoint: mvn
  args: ['--settings=cloudbuild-settings.xml', '--projects=serving', '-Drevision=ff-${SHORT_SHA}', '-Dtestbucket=${_TEST_BUCKET}', 'test']
- id: build-java
  waitFor: ['m2-cahce-pull']
  name: 'maven:${_MAVEN_VERSION}'
  entrypoint: mvn
  args: ['--settings=cloudbuild-settings.xml', '--projects=core,ingestion,serving', '-Drevision=ff-${SHORT_SHA}', '-DskipTests=true', '--batch-mode', 'package']
  timeout: 900s

# CLI (GO)
- id: gen-proto-go
  waitFor: ['-']
  name: 'gcr.io/konnekt-core/protoc-go:3.6.1'
  dir: '/workspace/protos'
  entrypoint: make
  args: ['gen-go']
- id: unit-test-mockgen
  waitFor: ['gen-proto-go']
  name: 'gcr.io/konnekt-core/mockgen:1.3.1'
  args: ['-package=mock', '-destination=cmd/mock/core_service.go', 'github.com/gojek/feast/protos/generated/go/feast/core', 'CoreServiceClient']
- id: unit-test-cli-setup
  waitFor: ['-']
  name: 'golang:1.13'
  args: ['go', 'get', '-u', 'github.com/jstemmer/go-junit-report']
- id: unit-test-cli-run
  waitFor: ['unit-test-mockgen', 'unit-test-cli-setup']
  name: 'golang:1.13'
  args: ['go', 'test', '-v', './cli/feast/...']
- id: build-cli
  waitFor: ['unit-test-cli-run']
  name: 'gcr.io/konnekt-core/protoc-go:3.6.1'
  dir: '/workspace/cli'
  entrypoint: make
  args: ['build-all']

# SDK (Python)
- id: gen-proto-python
  waitFor: ['-']
  name: 'gcr.io/konnekt-core/protoc-python:3.6.1'
  dir: '/workspace/protos'
  entrypoint: make
  args: ['gen-python']
- id: unit-test-python-sdk
  waitFor: ['gen-proto-python']
  name: 'python:3.7-buster'
  dir: '/workspace/sdk/python'
  env: ['SKIP_BIGQUERY_TEST=true'] # TODO: Configure project/permissions and re-enable
  entrypoint: sh
  args: ['-c', 'pip install -r requirements-test.txt && pip install . && pytest ./tests']
- id: install-python-sdk
  waitFor: ['unit-test-python-sdk']
  name: 'python:3.7-buster'
  entrypoint: sh
  args: ['-c', 'pip install -qe sdk/python']

# Integration Test (DISABLED TODO: Enable)
- id: integration-test-setup
  waitFor: ['build-java', 'build-cli', 'install-python-sdk']
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: sh
  args: ['-c', 'echo TODO: prepare_integration_test.sh']
- id: integration-test-run
  waitFor: ['integration-test-setup']
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: sh
  args: ['-c', 'echo TODO: install_feast_and_run_e2e_test.sh']
- id: integration-test-teardown
  waitFor: ['integration-test-run']
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: sh
  args: ['-c', 'echo TODO: cleanup_feast_installation.sh']

# Docker Images
- id: docker-build-core
  waitFor: ['build-java']
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'REVISION=ff-${SHORT_SHA}', '-t', 'gcr.io/${PROJECT_ID}/feast-core:ff-${SHORT_SHA}', '-f', 'Dockerfiles/core/Dockerfile', '.']
- id: docker-build-serving
  waitFor: ['build-java']
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'REVISION=ff-${SHORT_SHA}', '-t', 'gcr.io/${PROJECT_ID}/feast-serving:ff-${SHORT_SHA}', '-f', 'Dockerfiles/serving/Dockerfile', '.']

# Teardown
- id: m2-cahce-push
  waitFor: ['build-java']
  name: gcr.io/cloud-builders/gsutil
  args:
    - -o GSUtil:parallel_process_count=16
    - -o GSUtil:parallel_thread_count=1
    - -m
    - rsync
    - -j
    - pom,sha1
    - -r
    - /cache/m2
    - gs://dev-konnekt-data-deep-1-feast-tmp/cache/m2

images:
- gcr.io/${PROJECT_ID}/feast-core:ff-${SHORT_SHA}
- gcr.io/${PROJECT_ID}/feast-serving:ff-${SHORT_SHA}

options:
  machineType: N1_HIGHCPU_8
  env:
  - GO111MODULE=on
  - GOPATH=/cache/go
  - FEAST_VERSION=ff-${SHORT_SHA}
  volumes:
  - name: go_cache
    path: /cache/go
  - name: m2_cache
    path: /cache/m2

timeout: 1800s

substitutions:
  _TEST_BUCKET: dev-konnekt-data-deep-1-feast-tmp
  _MAVEN_VERSION: 3.6.2-jdk-11-slim

tags: ['team__konnekt', 'repo__konnekt_data_feast', 'commit__${SHORT_SHA}', 'slack__konnekt-se']
