steps:
- id: 'secrets'
  waitFor: ['-']
  name: 'alpine'
  args: ['sh', '-c', 'echo "$$SERVICE_ACCOUNT_B64" | base64 -d > /.secrets/gcp-credentials.json']
  secretEnv:
    - SERVICE_ACCOUNT_B64

# Setup
- id: m2-cache-init-dir
  waitFor: ['-']
  name: gcr.io/cloud-builders/gsutil
  entrypoint: sh
  args:
    - '-c'
    - |
      touch .keep && gsutil mv .keep ${_M2_CACHE_DIR}/.keep
- id: m2-cache-pull
  waitFor: ['m2-cache-init-dir']
  name: gcr.io/cloud-builders/gsutil
  args:
  - -o GSUtil:parallel_process_count=16
  - -o GSUtil:parallel_thread_count=1
  - -m
  - rsync
  - -j
  - pom,sha1
  - -r
  - ${_M2_CACHE_DIR}
  - /cache/m2

# JAVA
- id: unit-test-java
  waitFor: ['m2-cache-pull']
  name: 'maven:${_MAVEN_VERSION}'
  entrypoint: mvn
  args: ['--settings=cloudbuild-settings.xml', '-Drevision=ff-${SHORT_SHA}', 'test']
- id: build-java
  waitFor: ['unit-test-java']
  name: 'maven:${_MAVEN_VERSION}'
  entrypoint: mvn
  args: ['--settings=cloudbuild-settings.xml', '-Drevision=ff-${SHORT_SHA}', '-DskipTests=true', '--batch-mode', 'package']
  timeout: 900s
- id: create-deploy-poms
  waitFor: ['unit-test-java', 'build-java']
  name: 'alpine:latest'
  entrypoint: sh
  args:
  - '-c'
  - |
    for m in datatypes/java sdk/java; do
      sed -E 's^(<artifactId>)(feast-parent)(</artifactId>)^\1feast-ff-deploy\3^; s^(<relativePath>)(.*)(</relativePath>)^\1\2/pom-ff-deploy.xml\3^' $m/pom.xml > $m/pom-ff-deploy.xml
    done
- id: publish-java-sdk
  waitFor: ['create-deploy-poms']
  name: 'maven:${_MAVEN_VERSION}'
  entrypoint: mvn
  args: ['--settings=cloudbuild-settings.xml', '-Drevision=ff-${SHORT_SHA}','--file=pom-ff-deploy.xml', 'package', 'deploy:deploy']

# SDK (GO)
- id: compile-protos-go
  waitFor: ['-']
  name: 'gcr.io/konnekt-core/protoc-go:3.6.1'
  entrypoint: make
  args: ['compile-protos-go']
- id: unit-test-go-sdk-setup
  waitFor: ['-']
  name: 'golang:1.13'
  args: ['go', 'get', '-u', 'github.com/jstemmer/go-junit-report']
- id: unit-test-go-sdk-run
  waitFor: ['compile-protos-go', 'unit-test-go-sdk-setup']
  name: 'golang:1.13'
  dir: '/workspace/sdk/go'
  entrypoint: 'sh'
  args: ['-c', 'go test -v 2>&1 | tee /log/unit-test-cli-run']
- id: unit-test-go-sdk-report
  waitFor: ['unit-test-go-sdk-run']
  name: 'golang:1.13'
  dir: '/workspace/sdk/go'
  entrypoint: 'sh'
  args: ['-c', 'cat /log/unit-test-cli-run | $${GOPATH}/bin/go-junit-report > /log/golang-sdk-test-report.xml']

# SDK (Python)
- id: compile-protos-python
  waitFor: ['-']
  name: 'gcr.io/konnekt-core/protoc-python:3.7.5'
  dir: '/workspace'
  entrypoint: make
  args: ['compile-protos-python']
- id: unit-test-python-sdk
  waitFor: ['compile-protos-python']
  name: 'python:3.7-buster'
  dir: '/workspace/sdk/python'
  entrypoint: sh
  args: ['-c', 'pip install -r requirements-ci.txt && pip install -e . && pytest --junitxml=/log/python-sdk-test-report.xml']
- id: clean-git-state
  waitFor: ['unit-test-python-sdk']
  name: gcr.io/cloud-builders/git
  args: ['stash']
- id: git-unshallow-repo
  waitFor: ['unit-test-python-sdk']
  name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']
- id: upload-python-package
  waitFor: ['git-unshallow-repo']
  name: 'python:3.7-buster'
  dir: '/workspace/sdk/python'
  entrypoint: sh
  args: ['-c', 'python setup.py sdist && pip install twine && twine upload dist/*${SHORT_SHA}* --repository-url https://${_PYPI_REPO} -u ${_PYPI_USER} -p ${_PYPI_PWD}']
  env:
    - SHORT_SHA=${SHORT_SHA}
- id: install-python-sdk
  waitFor: ['upload-python-package']
  name: 'python:3.7-buster'
  entrypoint: sh
  args: ['-c', 'pip install -qe sdk/python']

# End-to-End Tests
- id: test-end-to-end
  waitFor: ['secrets', 'build-java', 'unit-test-go-sdk-report', 'install-python-sdk']
  name: 'maven:${_MAVEN_VERSION}'
  entrypoint: bash
  args: ['.prow/scripts/test-end-to-end.sh']
  env:
  - GOOGLE_APPLICATION_CREDENTIALS=/.secrets/gcp-credentials.json
  - SKIP_BUILD_JARS=true
  - GOOGLE_CLOUD_PROJECT=dev-konnekt-data-deep-1
  - TEMP_BUCKET=${_TEST_BUCKET}
  - JOBS_STAGING_LOCATION=gs://${_TEST_BUCKET}/e2e-staging
  - JAR_VERSION_SUFFIX=${SHORT_SHA}
- id: test-end-to-end-batch
  waitFor: ['secrets', 'build-java', 'unit-test-go-sdk-report', 'install-python-sdk']
  name: 'maven:${_MAVEN_VERSION}'
  entrypoint: bash
  args: ['.prow/scripts/test-end-to-end-batch.sh']
  env:
  - GOOGLE_APPLICATION_CREDENTIALS=/.secrets/gcp-credentials.json
  - SKIP_BUILD_JARS=true
  - GOOGLE_CLOUD_PROJECT=dev-konnekt-data-deep-1
  - TEMP_BUCKET=${_TEST_BUCKET}
  - JOBS_STAGING_LOCATION=gs://${_TEST_BUCKET}/e2e-staging
  - JAR_VERSION_SUFFIX=${SHORT_SHA}

# Docker Images
- id: docker-build-core
  waitFor: ['build-java']
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'REVISION=ff-${SHORT_SHA}', '-t', 'gcr.io/${PROJECT_ID}/feast-core:ff-${SHORT_SHA}', '-f', 'infra/docker/core/Dockerfile.ff', '.']
- id: docker-build-serving
  waitFor: ['build-java']
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'REVISION=ff-${SHORT_SHA}', '-t', 'gcr.io/${PROJECT_ID}/feast-serving:ff-${SHORT_SHA}', '-f', 'infra/docker/serving/Dockerfile.ff', '.']

# Teardown
- id: m2-cache-push
  waitFor: ['build-java']
  name: gcr.io/cloud-builders/gsutil
  args:
    - -o GSUtil:parallel_process_count=16
    - -o GSUtil:parallel_thread_count=1
    - -m
    - rsync
    - -j
    - pom,sha1
    - -r
    - /cache/m2
    - ${_M2_CACHE_DIR}

images:
- gcr.io/${PROJECT_ID}/feast-core:ff-${SHORT_SHA}
- gcr.io/${PROJECT_ID}/feast-serving:ff-${SHORT_SHA}

#artifacts:
#  objects:
#    location: 'gs://konnekt-artifacts/test-reports/feast/ff-${SHORT_SHA}/'
#    paths:
#    - /log/golang-sdk-test-report.xml

options:
  machineType: N1_HIGHCPU_8
  env:
  - GO111MODULE=on
  - GOPATH=/cache/go
  - FEAST_VERSION=ff-${SHORT_SHA}
  volumes:
  - name: secrets
    path: /.secrets
  - name: go_cache
    path: /cache/go
  - name: m2_cache
    path: /cache/m2
  - name: pip_cache
    path: /root/.cache/pip
  - name: logs
    path: /log

timeout: 1800s

# echo -n "$SECRET" | gcloud --project konnekt-core kms encrypt --plaintext-file=- --ciphertext-file=- --location=europe-west4 --keyring=cicd --key=ci | base64
secrets:
  - kmsKeyName: projects/konnekt-core/locations/europe-west4/keyRings/cicd/cryptoKeys/ci
    secretEnv:
      SERVICE_ACCOUNT_B64: "CiUAtvo7eauSn5JKjIODqxTaMBdMol9Z5vUEs/JR2CwuB7Zs3GVxEuMYAOrLjMDHpieeyLChRgmP/sDBtILolQTOGCUOD+DJJ5hLEbMU7UpmIOi2czwZbiVRrJ+Ya4d2mZNmw3O5lL2vvukTrWbOtzdQKfn9P3sJpdNy+VbAdL+1NWqpoMNXgr6vUJnpddH4afJyQmFKoYR+ySEfO9HW22ejPK6mblA/DSo9+5Hi2Nv0Sm55hG/klKUS0oVN1D77STLGLyTgzGWw44sNs11tFik7uMjN2YYQqIZx4SDgO01CckfMgrqcNTNnchl8X4FRjiZVmRNXGN34MJaQm15zVKBolZkXf7YbTgTETv87LWQqKD0U1/h9Tb2z1NAMXIvlnvBVWMeMkK3gvGTQMCw+vempfFxS6zeeu1kka9hjMb9TrtR/DSR6jH3jX4bZvj7+TeNhUwgcowYlfcANMiBg35i9oSNcrTjBgJJE4poU9PIbwRtPygP30IvTBcrosa1B8sCf6cUAItA/UJtb3SDHvl8V7tTfpmaOfMTVnLnDwOuKNmADcgB098HBy+0M3NUhbVMMTjr0+t92K/T1lkksYKI7+UzyitJlSsDPFJU+xeaXrExBBwUOCL+8VpSANUQoVB2AZfhqf4r7yJV5bPycWNOqPWDnKIrUeorMg4FQbS3Iv8ufkHBweNEyEqgyAlfaZO2UBZczNwnb1GHXKYOpns8tAFEx5AFa5UnCv9HM9yS4iB22gw1z/RbvP03AV3+owMizhwgNA75jOu4HoC7Gvhu0tuPqm6MZXFEY7zG2D/2XhtLZyBWZfUrPeZeNDiNBXo12DcVoCaJS/Gy6Otlj1BoZWpVV6kvJ/Hj9vB+/2dkGp67vtrV4DHTdwRadat593IqYg2Q4ZBloO751Riwj197XVxDHrG0H+W73r7Fh56kI+qSF/nZ1WpMkACHnXdLz8FirUFlbMnikokQM47sngvRYDRROUBhYdOQMmur4zPyFvTqIVYJuzIbJByxnvmQqjKU1P1/82ieQhJGuTHrkuuTA/DEqrE+1U15aYAKM8z6LDTlBOkcqv/S60gR+uzG9f5wiHiH2iMn+Rtw1odZCpq1slany3qmzhSfCrd7gsSd+HyxwZZPG/rmQHqsxci4nwqjcVNSiAdid19/Vj4VMsH7i+51CeTJ83CSzk6htRyfpw4sJHCaN96TMTgo3ATRHikSqdFD8NXDGWHkS7jU2tb0BbV6lOAN7yGICiz3PSsPBFj8GudJjO3UzbiYqo3YYrmRsUdUBCv9PJDfAJw5HIF4dTA/RokKqr2o7e1+ACUSJXBnGBVGNzFeW6fhAwgQg/Vo0vg3IznCW4H6Wug2XtKq0mvgksSWQeP7kd2hQIfuaiEsoqLHp2FgTIgsu0TbpQIYtNyP8ltOB9uKjVrpNVvUDXCWia8QdpyQpzh2mTMF8uu+Pm24FhOE9tHO1L476FnBltmyGFzSofeIzGd1p2VVIHOWrQdymLihR0dl3hjAq+l0Boz79JL0f5ETz/i4JzZk27mQ60++vqEVWjyQTZONK6O5KleQI+Rf2UFyoZPZZirnH14VkDKfHc12lLDSdvsdtO48p8JOfxvURfaHKN5sqg0dzBfWCEMhSOWnxZYqceZKVRoUj/TVuw+XJcW6+oUzKSAHyHj1oM2cXoGep0HumpsygdJNroh0lBDiksJDjASWnJTYUcj3Gbhpim8kb6fC5BilC4VoUGfwcwCcBmEZKDqnzuAZwaaVGBdJH0aKddJoXOhEOtfU3QLrInjRib2FZ1bdG2DDEL5J0lJbPe3+wS30Ho4Ri43zPV2oLQP3qSCP2hHubvWVp0QhsxloTy678hB2zCjjglDpneuXXCl3vLodXSnaAaKdpRcaZ8k8QJ14OQL+PCf4Uit+0pTBBEhSZwglJ4RUbibMRpBM4aMHwQOXckJ7jpf3IRaXZK30dlJ3IMkW/IGo28Q9KmQKhBGX5JiV1n0SaDsf1uOi4jFvjV3zzKOhtOSL6jdpHg6G91dv805NhtQ/MGJEOjzQ2Blvt/67PTooqlr0cjihs5ZN/p6XN4scD7t5UVu0SorJIEhJkFYQrM3I38lDwNj+Wy7PC6FWtYJTNVulQqvU/o1PbEklzqMRSrvUwXtHggqSdc4irpbMJj0mhc3zCPPUukf+ReMiI9M1sxnV06bklcFOGsa1Vw4hIzH0KqGu/Q1Cg0QQCigGXVJO6WTlxkO01SLh98yXF9HzU8OPcWZhIb+11Kjznto2Y1fEaPxqCQVQGN+l82ddFL+oM8alq9tbQmjOd4iNXHHukXGsNwjwfAzMhOOdzmwEZ34kEXw3ZzF6N9OfWUJX2I4GJnTyhyWXY7JNx8Nsu7cOii0R8TfmRgJsCuMNrHpJPRh3dz/v76qGxpmzKl8D/a7LSB78c1pTuhpMqeWv4tKXYdzEl5kPPZLqBzOxrDHL2PnEbrADzrszH+nLNKGS3da4krudXfYIULV2y5Mo8YQ/+nrXjhvRzIhTYlBakaSl654kjgpohb/5WU2VaCmthW+qOlydzm8buknZHLdcz5RxXpr54IfgnfpUkFMOKLaISbN8hVY7W2T72KdQWCJfepgkASZGb4yLYqGvq2aeaO3jQdsgghwRcMWR1HF3f7uYKupeHX7BHlX0dDk5tYCvF33toh4BaAb43K32N/eJCJJL2wviAt95fsrrJ513ExvTpU1axs5pvogEEg3FJD160DhGCFTt7uvZq8lurWkbT7Sp8IBW8l8RzIy/9I5Dn7WNMrED58R2TwXK0SKrQ6kaoO+ubcNDz4fIGLW7jbIQitXhE+3gZJ2kcaM06KX0DIjlVllKtnYB1FFDLfOB6pKbfEZ+D2RLQOyvm9WFFWJ5tfft1d5oWIisyuPwq/SVwkpj42Mt4jKJicvxg0nqOoSLtDJJcySn2JjVMZEfenN8IhQFdTgptrpLyCaR/OqW1/84+9ZvciWEvPTAHHYA9RbunpI9MFeqgQEi2qID4vUw6a/7iU0FNlfSxWa6X6U+2aIaQs0wb64AvDCtJemMxXczv0P5R0HQqqrA8ZV9SBW1YOvbhQ0CjKjK162V93rWn/nUNJjoVrsDnM1CSlcaW3rx+tqAjL/zAcSizZCGLz19tM1hxBXhWNLyRESX6d+NtNEqHrRyvpRzFEV/KXZm5KU+UsgF72k7hShKAKmstsggBkxWTzwKws1dZFuZYbpzlBqlKoqqijkW2iCFn0XpHIdFPBzzZZtmMTGFxxCGlOWeY67iu2f4YMzbWSuA5d4I5K0tkiC+liJmC1kxgEyKIFvt9hIYoj0EGs+/NOA6TnXF5a1ulu6GGw6LJLXBwjcKQyq7V10tlOzAvR3X2yZCrl1l1rQe44JCwdarm5SNkGrtwubjcw2qoXC4xrDtkocP7dHCD/8fn8/GEHVaSiXsSLkCZZh3ZcKiPr1MN9UDzVLTmCux72ifoj/y557Laj3hqb7XdzHZSmxXx0JjXxWCTT2RdT5oxUqmlphUlz0alqE86yzlj/WzoZCpCXmTtULbWug/Q+3QQRVJ48ht1ok/mmh1qt6QKbt+VUDDZLhVLUElp9cvSbvcMdzzXrEkz/+lV597jORpoLc4903tS+UCvxGrrO1Iwv+Iua2xsKqmF0951CLbZYj1XBTvlvOsJtyg4RU3UWkg5MhqGS3UgnSiPatbeMrjS+xDTBkJO1tx8k0s6xcbk5B8opIR6cAbdjbUaDSCRSaJRc+lKTX20dmt8/1U1WGT8JZOcYAbhJ3cxy915DHCVjK7x7/J05We2ZvXiwCzckYdZnJd9AZhNZAXV+SldsE57X42HgG83m17qA25PROTYa9Vp7nPfV1w+xCN9+Sh0/D8BfWsYaHjyjrdPVwYtb/MmgIlCzgYG9vas4jq8ZDBNM8lUM+8jbgC4WvZQ4/pPq9pgOT3LhredpnMy6yAtM9J86lwTF0hutpQisKlRck1sz7I8vXtvR4rbDZrE23zk6cSOXoUS9oqHWLwwmJpJ7wwUp2ptUSBvzpu5Z/gtoeSPYfId6QDTScisL5EXZCA3UhAlRE15O9Af+Pzy1/AnJLgKXhfHYTfyEmL/SJoFaEyg2Bj21ZWGXYZz+YqMXTY+y/94ZoUhmwTHqWckwcA/EkB7WzrWAOV9+B2IksjZuY+LX5rBsgqRAe9NSktooPnSnwIvbo5lH2iUaF+FuK/AHPk/0FZy8KXwjontRBX+UIQvMyoMkibwRqQD0UpXao45gPjbthhYy1sQKChmMZNhCo8oQ9Mw"

substitutions:
  _TEST_BUCKET: dev-konnekt-data-deep-1-feast-tmp
  _MAVEN_VERSION: 3.6.2-jdk-11
  _M2_CACHE_DIR: 'gs://dev-konnekt-data-deep-1-feast-tmp/cache/m2'

tags: ['team__konnekt', 'repo__konnekt_data_feast', 'commit__${SHORT_SHA}', 'slack__konnekt-feature-store']
