steps:

# Setup
- id: m2-cahce-pull
  waitFor: ['-']
  name: gcr.io/cloud-builders/gsutil
  args:
  - -o GSUtil:parallel_process_count=16
  - -o GSUtil:parallel_thread_count=1
  - -m
  - rsync
  - -j
  - pom,sha1
  - -r
  - gs://dev-konnekt-data-deep-1-feast-tmp/cache/m2
  - /cache/m2

# JAVA
- id: unit-test
  waitFor: ['m2-cahce-pull']
  name: 'maven:${_MAVEN_VERSION}'
  entrypoint: mvn
  args: ['--settings=cloudbuild-settings.xml', '-Drevision=ff-${SHORT_SHA}', '-Dtestbucket=${_TEST_BUCKET}', 'test']
- id: build-java
  waitFor: ['unit-test']
  name: 'maven:${_MAVEN_VERSION}'
  entrypoint: mvn
  args: ['--settings=cloudbuild-settings.xml', '-Drevision=ff-${SHORT_SHA}', '-DskipTests=true', '--batch-mode', 'package']
  timeout: 900s

# SDK (GO)
- id: gen-proto-go
  waitFor: ['-']
  name: 'gcr.io/konnekt-core/protoc-go:3.6.1'
  dir: '/workspace/protos'
  entrypoint: make
  args: ['gen-go']
- id: unit-test-go-sdk-setup
  waitFor: ['-']
  name: 'golang:1.13'
  args: ['go', 'get', '-u', 'github.com/jstemmer/go-junit-report']
- id: unit-test-go-sdk-run
  waitFor: ['gen-proto-go', 'unit-test-go-sdk-setup']
  name: 'golang:1.13'
  dir: '/workspace/sdk/go'
  entrypoint: 'sh'
  args: ['-c', 'go test -v 2>&1 | tee /log/unit-test-cli-run']
- id: unit-test-go-sdk-report
  waitFor: ['unit-test-go-sdk-run']
  name: 'golang:1.13'
  dir: '/workspace/sdk/go'
  entrypoint: 'sh'
  args: ['-c', 'cat /log/unit-test-cli-run | $${GOPATH}/bin/go-junit-report > /log/golang-sdk-test-report.xml']

# SDK (Python)
- id: gen-proto-python
  waitFor: ['-']
  name: 'gcr.io/konnekt-core/protoc-python@sha256:61421f32abe11acac6a9aa6356a1b3cf009daa0fc3feb3d875e098fde422f8b0'
  dir: '/workspace/protos'
  entrypoint: make
  args: ['gen-python']
- id: unit-test-python-sdk
  waitFor: ['gen-proto-python']
  name: 'python:3.7-buster'
  dir: '/workspace/sdk/python'
  entrypoint: sh
  args: ['-c', 'pip install -r requirements-ci.txt && pip install -e . && pytest --junitxml=/log/python-sdk-test-report.xml']
- id: upload-python-package
  waitFor: ['unit-test-python-sdk']
  name: 'python:3.7-buster'
  dir: '/workspace/sdk/python'
  entrypoint: sh
  args: ['-c', 'python setup.py sdist && pip install twine && twine upload dist/*${SHORT_SHA}* --repository-url https://${_PYPI_REPO} -u ${_PYPI_USER} -p ${_PYPI_PWD}']
  env:
    - SHORT_SHA=${SHORT_SHA}

- id: install-python-sdk
  waitFor: ['upload-python-package']
  name: 'python:3.7-buster'
  entrypoint: sh
  args: ['-c', 'pip install -qe sdk/python']

# Integration Test (DISABLED TODO: Enable)
- id: integration-test-setup
  waitFor: ['build-java', 'unit-test-go-sdk-report', 'install-python-sdk']
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: sh
  args: ['-c', 'echo TODO: prepare_integration_test.sh']
- id: integration-test-run
  waitFor: ['integration-test-setup']
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: sh
  args: ['-c', 'echo TODO: install_feast_and_run_e2e_test.sh']
- id: integration-test-teardown
  waitFor: ['integration-test-run']
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: sh
  args: ['-c', 'echo TODO: cleanup_feast_installation.sh']

# Docker Images
- id: docker-build-core
  waitFor: ['build-java']
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'REVISION=ff-${SHORT_SHA}', '-t', 'gcr.io/${PROJECT_ID}/feast-core:ff-${SHORT_SHA}', '-f', 'infra/docker/core/Dockerfile', '.']
- id: docker-build-serving
  waitFor: ['build-java']
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'REVISION=ff-${SHORT_SHA}', '-t', 'gcr.io/${PROJECT_ID}/feast-serving:ff-${SHORT_SHA}', '-f', 'infra/docker/serving/Dockerfile', '.']

# Teardown
- id: m2-cahce-push
  waitFor: ['build-java']
  name: gcr.io/cloud-builders/gsutil
  args:
    - -o GSUtil:parallel_process_count=16
    - -o GSUtil:parallel_thread_count=1
    - -m
    - rsync
    - -j
    - pom,sha1
    - -r
    - /cache/m2
    - gs://dev-konnekt-data-deep-1-feast-tmp/cache/m2

images:
- gcr.io/${PROJECT_ID}/feast-core:ff-${SHORT_SHA}
- gcr.io/${PROJECT_ID}/feast-serving:ff-${SHORT_SHA}

#artifacts:
#  objects:
#    location: 'gs://konnekt-artifacts/test-reports/feast/ff-${SHORT_SHA}/'
#    paths:
#    - /log/golang-sdk-test-report.xml

options:
  machineType: N1_HIGHCPU_8
  env:
  - GO111MODULE=on
  - GOPATH=/cache/go
  - FEAST_VERSION=ff-${SHORT_SHA}
  volumes:
  - name: go_cache
    path: /cache/go
  - name: m2_cache
    path: /cache/m2
  - name: logs
    path: /log

timeout: 1800s

substitutions:
  _TEST_BUCKET: dev-konnekt-data-deep-1-feast-tmp
  _MAVEN_VERSION: 3.6.2-jdk-11-slim

tags: ['team__konnekt', 'repo__konnekt_data_feast', 'commit__${SHORT_SHA}', 'slack__konnekt-se']
