heapOpts: -Xmx1024m -Xms1024m
persistence:
  enabled: false
resources:
  limits:
    cpu: 1200m
    memory: 1280Mi
  requests:
    cpu: 50m
    memory: 1024Mi
zookeeper:
  enabled: false
externalZookeeper:
  servers: feast-zookeeper:2181
