version: "3.7"

services:
  databricks-emulator:
    build:
      context: ../..
      dockerfile: infra/docker/databricks-emulator/Dockerfile
    image: ${FEAST_DATABRICKS_EMULATOR_IMAGE:-feast-databricks-emulator-dev}:${FEAST_VERSION}
    volumes:
      - ${FEAST_BATCH_JOB_STAGING_LOCATION}:${FEAST_BATCH_JOB_STAGING_LOCATION}
    restart: on-failure
    ports:
      - 9080:8080
