name: deploy-to-aks

on:
  push:
    branches:
    - master
    paths:
    - 'infra/charts/**'
    - 'infra/desired-state/**'
    - 'infra/scripts/deploy-to-aks.sh'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - uses: actions/checkout@v1

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: make deploy-to-azure script executable
        run: chmod +x ./infra/scripts/deploy-to-aks.sh

      - name: deploy
        run: ./infra/scripts/deploy-to-aks.sh
