name: unit tests

on: [push, pull_request]

jobs:
  unit-test-java:
    runs-on: ubuntu-latest
    container: gcr.io/kf-feast/feast-ci:latest
    name: unit test java
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: test java
        run: make test-java-with-coverage
      - uses: actions/upload-artifact@v2
        with:
          name: java-coverage-report
          path: ${{ github.workspace }}/docs/coverage/java/target/site/jacoco-aggregate/

  unit-test-java-8:
    runs-on: ubuntu-latest
    container: gcr.io/kf-feast/feast-ci:latest
    name: unit test java 8
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: test java
        # TODO add JDK 8 to gcr.io/kf-feast/feast-ci image
        run: |
          apt update
          apt install -y software-properties-common
          wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add -
          add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
          apt update
          apt install -y adoptopenjdk-8-hotspot
          mvn -B test -pl spark/spark-ingestion-job,spark/spark-historical-retriever-job -Djvm=/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin/java

  unit-test-python:
    runs-on: ubuntu-latest
    container: gcr.io/kf-feast/feast-ci:latest
    name: unit test python
    steps:
      - uses: actions/checkout@v2
      - name: install python
        run: make install-python
      - name: test python
        run: make test-python

  unit-test-go:
    runs-on: ubuntu-latest
    container: gcr.io/kf-feast/feast-ci:latest
    name: unit test go
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: make compile-protos-go
      - name: test go
        run: make test-go
